[package]
name = "callisto-vcs"
version = "0.8.0"
edition.workspace = true
license = "MIT"
description = "Callisto Release Engine — Git access for polyglot monorepos."
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
callisto-model = { path = "../callisto-model", version = "0.8.0" }
thiserror = { workspace = true }
miette = { workspace = true }
globset = { workspace = true }
dunce = { workspace = true }

[dev-dependencies]
callisto-model = { path = "../callisto-model", features = ["test-util"] }
tempfile = { workspace = true }
