version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      routine-actions:
        applies-to: version-updates
        patterns: ["*"]
      security-actions:
        applies-to: security-updates
        patterns: ["*"]
