[package]
name = "callisto-changelog"
version.workspace = true
edition.workspace = true
license = "AGPL-3.0-only"
description = "Callisto Release Engine — Automated changelog compiler and history renderer."
repository.workspace = true
readme = "README.md"

[dependencies]
callisto-model = { path = "../callisto-model", version = "0.3.0" }
tempfile = { workspace = true }
thiserror = { workspace = true }
miette = { workspace = true }

[dev-dependencies]
callisto-model = { path = "../callisto-model", features = ["test-util"] }
